# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.



development:
  api_key: 06cd8d85b17a630427949284e32864a4
  secret_key: 3db7c5bc0cc01d72ec8860c009579ab0
  canvas_page_name: fasterlighter
  callback_url: http://dolores.fasterlighterbetter.com/authenticate
  pretty_errors: true
  set_asset_host_to_callback_url: false

test:
  api_key: 06cd8d85b17a630427949284e32864a4
  secret_key: 3db7c5bc0cc01d72ec8860c009579ab0
  canvas_page_name: fasterlighter
  callback_url: http://dolores.fasterlighterbetter.com/authenticate
  set_asset_host_to_callback_url: false

production:
  api_key: 06cd8d85b17a630427949284e32864a4
  secret_key: 3db7c5bc0cc01d72ec8860c009579ab0
  canvas_page_name: fasterlighter
  callback_url: http://dolores.fasterlighterbetter.com/authenticate
  set_asset_host_to_callback_url: false
