OrphanedPagesJob:
  every: 1m
  queue: high
  args: 
  class: OrphanedPagesJob
  description: "This job queues all orphaned page for url matching to provider"

ProviderablePagesJob:
  every: 1m
  queue: high
  args: 
  class: ProviderablePagesJob
  description: "This job queues all providerable pages for author lookup"

SpiderablePagesJob:
  every: 1m
  queue: high
  args: 
  class: SpiderablePagesJob
  description: "This job queues all spiderable pages to discover page author link"


