OrphanedPagesJob:
  every: 10s
  queue: high
  args: 
  class: OrphanedPagesJob
  description: "This job queues all orphaned page for url matching to provider"

ProviderablePagesJob:
  every: 10s
  queue: high
  args: 
  class: ProviderablePagesJob
  description: "This job queues all providerable pages for author lookup"

SpiderablePagesJob:
  every: 10s
  queue: high
  args:
  class: SpiderablePagesJob
  description: "This job queues all spiderable pages to discover page author link"

StrangerIdentitiesJob:
  every: 10s
  queues: high
  args:
  class: StrangerIdentitiesJob
  description: "This job queues stranger identities to see if they should be wanted."

WantedIdentitiesJob:
  every: 10s
  queues: high
  args:
  class: WantedIdentitiesJob
  description: "This job queues wanted identities for messaging."

UsersJob:
  every: 10s
  queues: high
  args:
  class: UsersJob
  description: ""

EarnedChecksJob:
  every: 10s
  queues: high
  args:
  class: EarnedChecksJob
  description: ""
