# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

roles = Role.create([
  { :name => 'Patron' },
  { :name => 'Publisher' },
  { :name => 'Guest' },
  { :name => 'Administrator' },
  { :name => 'Developer' }
])

card_types = CardType.create([
  { :name => 'visa' },
  { :name => 'mastercard' },
  { :name => 'discover' },
  { :name => 'americanexpress' }
])

(1..31).each do |id|
  BillingPeriod.create(:id => id)

configurations = Configuration.create([
  { :property => 'fee_percent', :value => '7'}
])

states = State.create([
  { :name => 'Alabama', :abbreviation => 'AL' },
  { :name => 'Alaska', :abbreviation => 'AK' },
  { :name => 'American Samoa', :abbreviation => 'AS' },
  { :name => 'Arizona', :abbreviation => 'AZ' },
  { :name => 'Arkansas', :abbreviation => 'AR' },
  { :name => 'California', :abbreviation => 'CA' },
  { :name => 'Colorado', :abbreviation => 'CO' },
  { :name => 'Connecticut', :abbreviation => 'CT' },
  { :name => 'Delaware', :abbreviation => 'DE' },
  { :name => 'District of Columbia', :abbreviation => 'DC' },
  { :name => 'Federated States of Micronesia', :abbreviation => 'FM' },
  { :name => 'Florida', :abbreviation => 'FL' },
  { :name => 'Georgia', :abbreviation => 'GA' },
  { :name => 'Guam', :abbreviation => 'GU' },
  { :name => 'Hawaii', :abbreviation => 'HI' },
  { :name => 'Idaho', :abbreviation => 'ID' },
  { :name => 'Illinois', :abbreviation => 'IL' },
  { :name => 'Indiana', :abbreviation => 'IN' },
  { :name => 'Iowa', :abbreviation => 'IA' },
  { :name => 'Kansas', :abbreviation => 'KS' },
  { :name => 'Kentucky', :abbreviation => 'KY' },
  { :name => 'Louisiana', :abbreviation => 'LA' },
  { :name => 'Maine', :abbreviation => 'ME' },
  { :name => 'Marshall Islands', :abbreviation => 'MH' },
  { :name => 'Maryland', :abbreviation => 'MD' },
  { :name => 'Massachusetts', :abbreviation => 'MA' },
  { :name => 'Michigan', :abbreviation => 'MI' },
  { :name => 'Minnesota', :abbreviation => 'MN' },
  { :name => 'MISSISSIPPI', :abbreviation => 'MS' },
  { :name => 'MISSOURI', :abbreviation => 'MO' },
  { :name => 'MONTANA', :abbreviation => 'MT' },
  { :name => 'NEBRASKA', :abbreviation => 'NE' },
  { :name => 'NEVADA', :abbreviation => 'NV' },
  { :name => 'New Hampshire', :abbreviation => 'NH' },
  { :name => 'New Jersey', :abbreviation => 'NJ' },
  { :name => 'New Mexico', :abbreviation => 'NM' },
  { :name => 'New York', :abbreviation => 'NY' },
  { :name => 'North Carolina', :abbreviation => 'NC' },
  { :name => 'North Dakota', :abbreviation => 'ND' },
  { :name => 'Northern Mariana Islands', :abbreviation => 'MP' },
  { :name => 'Ohio', :abbreviation => 'OH' },
  { :name => 'Oklahoma', :abbreviation => 'OK' },
  { :name => 'Oregon', :abbreviation => 'OR' },
  { :name => 'Palau', :abbreviation => 'PW' },
  { :name => 'Pennsylvania', :abbreviation => 'PA' },
  { :name => 'Puerto Rico', :abbreviation => 'PR' },
  { :name => 'Rhode Island', :abbreviation => 'RI' },
  { :name => 'South Carolina', :abbreviation => 'SC' },
  { :name => 'South Dakota', :abbreviation => 'SD' },
  { :name => 'Tennessee', :abbreviation => 'TN' },
  { :name => 'Texas', :abbreviation => 'TX' },
  { :name => 'Utah', :abbreviation => 'UT' },
  { :name => 'Vermont', :abbreviation => 'VT' },
  { :name => 'Virgin Islands', :abbreviation => 'VI' },
  { :name => 'Virginia', :abbreviation => 'VA' },
  { :name => 'Washington', :abbreviation => 'WA' },
  { :name => 'West Virginia', :abbreviation => 'WV' },
  { :name => 'Wisconsin', :abbreviation => 'WI' },
  { :name => 'Wyoming', :abbreviation => 'WY' },
  { :name => 'Armed Forces Africa', :abbreviation => 'AE' },
  { :name => 'Armed Forces Americas', :abbreviation => 'AA' }
])

countries = Country.create([
  { :abbreviation => "AD", :name => "Andorra" },
  { :abbreviation => "AE", :name => "United Arab Emirates" },
  { :abbreviation => "AF", :name => "Afghanistan" },
  { :abbreviation => "AG", :name => "Antigua & Barbuda" },
  { :abbreviation => "AI", :name => "Anguilla" },
  { :abbreviation => "AL", :name => "Albania" },
  { :abbreviation => "AM", :name => "Armenia" },
  { :abbreviation => "AN", :name => "Netherlands Antilles" },
  { :abbreviation => "AO", :name => "Angola" },
  { :abbreviation => "AQ", :name => "Antarctica" },
  { :abbreviation => "AR", :name => "Argentina" },
  { :abbreviation => "AS", :name => "American Samoa" },
  { :abbreviation => "AT", :name => "Austria" },
  { :abbreviation => "AU", :name => "Australia" },
  { :abbreviation => "AW", :name => "Aruba" },
  { :abbreviation => "AZ", :name => "Azerbaijan" },
  { :abbreviation => "BA", :name => "Bosnia and Herzegovina" },
  { :abbreviation => "BB", :name => "Barbados" },
  { :abbreviation => "BD", :name => "Bangladesh" },
  { :abbreviation => "BE", :name => "Belgium" },
  { :abbreviation => "BF", :name => "Burkina Faso" },
  { :abbreviation => "BG", :name => "Bulgaria" },
  { :abbreviation => "BH", :name => "Bahrain" },
  { :abbreviation => "BI", :name => "Burundi" },
  { :abbreviation => "BJ", :name => "Benin" },
  { :abbreviation => "BM", :name => "Bermuda" },
  { :abbreviation => "BN", :name => "Brunei Darussalam" },
  { :abbreviation => "BO", :name => "Bolivia" },
  { :abbreviation => "BR", :name => "Brazil" },
  { :abbreviation => "BS", :name => "Bahama" },
  { :abbreviation => "BT", :name => "Bhutan" },
  { :abbreviation => "BV", :name => "Bouvet Island" },
  { :abbreviation => "BW", :name => "Botswana" },
  { :abbreviation => "BY", :name => "Belarus" },
  { :abbreviation => "BZ", :name => "Belize" },
  { :abbreviation => "CA", :name => "Canada" },
  { :abbreviation => "CC", :name => "Cocos (Keeling) Islands" },
  { :abbreviation => "CF", :name => "Central African Republic" },
  { :abbreviation => "CG", :name => "Congo" },
  { :abbreviation => "CH", :name => "Switzerland" },
  { :abbreviation => "CI", :name => "Côte D'ivoire (Ivory Coast)" },
  { :abbreviation => "CK", :name => "Cook Iislands" },
  { :abbreviation => "CL", :name => "Chile" },
  { :abbreviation => "CM", :name => "Cameroon" },
  { :abbreviation => "CN", :name => "China" },
  { :abbreviation => "CO", :name => "Colombia" },
  { :abbreviation => "CR", :name => "Costa Rica" },
  { :abbreviation => "CU", :name => "Cuba" },
  { :abbreviation => "CV", :name => "Cape Verde" },
  { :abbreviation => "CX", :name => "Christmas Island" },
  { :abbreviation => "CY", :name => "Cyprus" },
  { :abbreviation => "CZ", :name => "Czech Republic" },
  { :abbreviation => "DE", :name => "Germany" },
  { :abbreviation => "DJ", :name => "Djibouti" },
  { :abbreviation => "DK", :name => "Denmark" },
  { :abbreviation => "DM", :name => "Dominica" },
  { :abbreviation => "DO", :name => "Dominican Republic" },
  { :abbreviation => "DZ", :name => "Algeria" },
  { :abbreviation => "EC", :name => "Ecuador" },
  { :abbreviation => "EE", :name => "Estonia" },
  { :abbreviation => "EG", :name => "Egypt" },
  { :abbreviation => "EH", :name => "Western Sahara" },
  { :abbreviation => "ER", :name => "Eritrea" },
  { :abbreviation => "ES", :name => "Spain" },
  { :abbreviation => "ET", :name => "Ethiopia" },
  { :abbreviation => "FI", :name => "Finland" },
  { :abbreviation => "FJ", :name => "Fiji" },
  { :abbreviation => "FK", :name => "Falkland Islands (Malvinas)" },
  { :abbreviation => "FM", :name => "Micronesia" },
  { :abbreviation => "FO", :name => "Faroe Islands" },
  { :abbreviation => "FR", :name => "France" },
  { :abbreviation => "FX", :name => "France, Metropolitan" },
  { :abbreviation => "GA", :name => "Gabon" },
  { :abbreviation => "GB", :name => "United Kingdom (Great Britain)" },
  { :abbreviation => "GD", :name => "Grenada" },
  { :abbreviation => "GE", :name => "Georgia" },
  { :abbreviation => "GF", :name => "French Guiana" },
  { :abbreviation => "GH", :name => "Ghana" },
  { :abbreviation => "GI", :name => "Gibraltar" },
  { :abbreviation => "GL", :name => "Greenland" },
  { :abbreviation => "GM", :name => "Gambia" },
  { :abbreviation => "GN", :name => "Guinea" },
  { :abbreviation => "GP", :name => "Guadeloupe" },
  { :abbreviation => "GQ", :name => "Equatorial Guinea" },
  { :abbreviation => "GR", :name => "Greece" },
  { :abbreviation => "GS", :name => "South Georgia and the South Sandwich Islands" },
  { :abbreviation => "GT", :name => "Guatemala" },
  { :abbreviation => "GU", :name => "Guam" },
  { :abbreviation => "GW", :name => "Guinea-Bissau" },
  { :abbreviation => "GY", :name => "Guyana" },
  { :abbreviation => "HK", :name => "Hong Kong" },
  { :abbreviation => "HM", :name => "Heard & McDonald Islands" },
  { :abbreviation => "HN", :name => "Honduras" },
  { :abbreviation => "HR", :name => "Croatia" },
  { :abbreviation => "HT", :name => "Haiti" },
  { :abbreviation => "HU", :name => "Hungary" },
  { :abbreviation => "ID", :name => "Indonesia" },
  { :abbreviation => "IE", :name => "Ireland" },
  { :abbreviation => "IL", :name => "Israel" },
  { :abbreviation => "IN", :name => "India" },
  { :abbreviation => "IO", :name => "British Indian Ocean Territory" },
  { :abbreviation => "IQ", :name => "Iraq" },
  { :abbreviation => "IR", :name => "Islamic Republic of Iran" },
  { :abbreviation => "IS", :name => "Iceland" },
  { :abbreviation => "IT", :name => "Italy" },
  { :abbreviation => "JM", :name => "Jamaica" },
  { :abbreviation => "JO", :name => "Jordan" },
  { :abbreviation => "JP", :name => "Japan" },
  { :abbreviation => "KE", :name => "Kenya" },
  { :abbreviation => "KG", :name => "Kyrgyzstan" },
  { :abbreviation => "KH", :name => "Cambodia" },
  { :abbreviation => "KI", :name => "Kiribati" },
  { :abbreviation => "KM", :name => "Comoros" },
  { :abbreviation => "KN", :name => "St. Kitts and Nevis" },
  { :abbreviation => "KP", :name => "Korea, Democratic People's Republic of" },
  { :abbreviation => "KR", :name => "Korea, Republic of" },
  { :abbreviation => "KW", :name => "Kuwait" },
  { :abbreviation => "KY", :name => "Cayman Islands" },
  { :abbreviation => "KZ", :name => "Kazakhstan" },
  { :abbreviation => "LA", :name => "Lao People's Democratic Republic" },
  { :abbreviation => "LB", :name => "Lebanon" },
  { :abbreviation => "LC", :name => "Saint Lucia" },
  { :abbreviation => "LI", :name => "Liechtenstein" },
  { :abbreviation => "LK", :name => "Sri Lanka" },
  { :abbreviation => "LR", :name => "Liberia" },
  { :abbreviation => "LS", :name => "Lesotho" },
  { :abbreviation => "LT", :name => "Lithuania" },
  { :abbreviation => "LU", :name => "Luxembourg" },
  { :abbreviation => "LV", :name => "Latvia" },
  { :abbreviation => "LY", :name => "Libyan Arab Jamahiriya" },
  { :abbreviation => "MA", :name => "Morocco" },
  { :abbreviation => "MC", :name => "Monaco" },
  { :abbreviation => "MD", :name => "Moldova, Republic of" },
  { :abbreviation => "MG", :name => "Madagascar" },
  { :abbreviation => "MH", :name => "Marshall Islands" },
  { :abbreviation => "ML", :name => "Mali" },
  { :abbreviation => "MN", :name => "Mongolia" },
  { :abbreviation => "MM", :name => "Myanmar" },
  { :abbreviation => "MO", :name => "Macau" },
  { :abbreviation => "MP", :name => "Northern Mariana Islands" },
  { :abbreviation => "MQ", :name => "Martinique" },
  { :abbreviation => "MR", :name => "Mauritania" },
  { :abbreviation => "MS", :name => "Monserrat" },
  { :abbreviation => "MT", :name => "Malta" },
  { :abbreviation => "MU", :name => "Mauritius" },
  { :abbreviation => "MV", :name => "Maldives" },
  { :abbreviation => "MW", :name => "Malawi" },
  { :abbreviation => "MX", :name => "Mexico" },
  { :abbreviation => "MY", :name => "Malaysia" },
  { :abbreviation => "MZ", :name => "Mozambique" },
  { :abbreviation => "NA", :name => "Namibia" },
  { :abbreviation => "NC", :name => "New Caledonia" },
  { :abbreviation => "NE", :name => "Niger" },
  { :abbreviation => "NF", :name => "Norfolk Island" },
  { :abbreviation => "NG", :name => "Nigeria" },
  { :abbreviation => "NI", :name => "Nicaragua" },
  { :abbreviation => "NL", :name => "Netherlands" },
  { :abbreviation => "NO", :name => "Norway" },
  { :abbreviation => "NP", :name => "Nepal" },
  { :abbreviation => "NR", :name => "Nauru" },
  { :abbreviation => "NU", :name => "Niue" },
  { :abbreviation => "NZ", :name => "New Zealand" },
  { :abbreviation => "OM", :name => "Oman" },
  { :abbreviation => "PA", :name => "Panama" },
  { :abbreviation => "PE", :name => "Peru" },
  { :abbreviation => "PF", :name => "French Polynesia" },
  { :abbreviation => "PG", :name => "Papua New Guinea" },
  { :abbreviation => "PH", :name => "Philippines" },
  { :abbreviation => "PK", :name => "Pakistan" },
  { :abbreviation => "PL", :name => "Poland" },
  { :abbreviation => "PM", :name => "St. Pierre & Miquelon" },
  { :abbreviation => "PN", :name => "Pitcairn" },
  { :abbreviation => "PR", :name => "Puerto Rico" },
  { :abbreviation => "PT", :name => "Portugal" },
  { :abbreviation => "PW", :name => "Palau" },
  { :abbreviation => "PY", :name => "Paraguay" },
  { :abbreviation => "QA", :name => "Qatar" },
  { :abbreviation => "RE", :name => "Réunion" },
  { :abbreviation => "RO", :name => "Romania" },
  { :abbreviation => "RU", :name => "Russian Federation" },
  { :abbreviation => "RW", :name => "Rwanda" },
  { :abbreviation => "SA", :name => "Saudi Arabia" },
  { :abbreviation => "SB", :name => "Solomon Islands" },
  { :abbreviation => "SC", :name => "Seychelles" },
  { :abbreviation => "SD", :name => "Sudan" },
  { :abbreviation => "SE", :name => "Sweden" },
  { :abbreviation => "SG", :name => "Singapore" },
  { :abbreviation => "SH", :name => "St. Helena" },
  { :abbreviation => "SI", :name => "Slovenia" },
  { :abbreviation => "SJ", :name => "Svalbard & Jan Mayen Islands" },
  { :abbreviation => "SK", :name => "Slovakia" },
  { :abbreviation => "SL", :name => "Sierra Leone" },
  { :abbreviation => "SM", :name => "San Marino" },
  { :abbreviation => "SN", :name => "Senegal" },
  { :abbreviation => "SO", :name => "Somalia" },
  { :abbreviation => "SR", :name => "Suriname" },
  { :abbreviation => "ST", :name => "Sao Tome & Principe" },
  { :abbreviation => "SV", :name => "El Salvador" },
  { :abbreviation => "SY", :name => "Syrian Arab Republic" },
  { :abbreviation => "SZ", :name => "Swaziland" },
  { :abbreviation => "TC", :name => "Turks & Caicos Islands" },
  { :abbreviation => "TD", :name => "Chad" },
  { :abbreviation => "TF", :name => "French Southern Territories" },
  { :abbreviation => "TG", :name => "Togo" },
  { :abbreviation => "TH", :name => "Thailand" },
  { :abbreviation => "TJ", :name => "Tajikistan" },
  { :abbreviation => "TK", :name => "Tokelau" },
  { :abbreviation => "TM", :name => "Turkmenistan" },
  { :abbreviation => "TN", :name => "Tunisia" },
  { :abbreviation => "TO", :name => "Tonga" },
  { :abbreviation => "TP", :name => "East Timor" },
  { :abbreviation => "TR", :name => "Turkey" },
  { :abbreviation => "TT", :name => "Trinidad & Tobago" },
  { :abbreviation => "TV", :name => "Tuvalu" },
  { :abbreviation => "TW", :name => "Taiwan, Province of China" },
  { :abbreviation => "TZ", :name => "Tanzania, United Republic of" },
  { :abbreviation => "UA", :name => "Ukraine" },
  { :abbreviation => "UG", :name => "Uganda" },
  { :abbreviation => "UM", :name => "United States Minor Outlying Islands" },
  { :abbreviation => "US", :name => "United States of America" },
  { :abbreviation => "UY", :name => "Uruguay" },
  { :abbreviation => "UZ", :name => "Uzbekistan" },
  { :abbreviation => "VA", :name => "Vatican City State (Holy See)" },
  { :abbreviation => "VC", :name => "St. Vincent & the Grenadines" },
  { :abbreviation => "VE", :name => "Venezuela" },
  { :abbreviation => "VG", :name => "British Virgin Islands" },
  { :abbreviation => "VI", :name => "United States Virgin Islands" },
  { :abbreviation => "VN", :name => "Viet Nam" },
  { :abbreviation => "VU", :name => "Vanuatu" },
  { :abbreviation => "WF", :name => "Wallis & Futuna Islands" },
  { :abbreviation => "WS", :name => "Samoa" },
  { :abbreviation => "YE", :name => "Yemen" },
  { :abbreviation => "YT", :name => "Mayotte" },
  { :abbreviation => "YU", :name => "Yugoslavia" },
  { :abbreviation => "ZA", :name => "South Africa" },
  { :abbreviation => "ZM", :name => "Zambia" },
  { :abbreviation => "ZR", :name => "Zaire" },
  { :abbreviation => "ZW", :name => "Zimbabwe" },
  { :abbreviation => "ZZ", :name => "Unknown or unspecified country" }
])
end
