#!/usr/bin/env ruby
ENV['RAILS_ENV'] = ARGV.shift || 'development'
require File.expand_path(File.join(File.dirname(__FILE__),"../config/environment"))

user = User.new
user.email                 = 'test@test.com'
user.password              = 'test'
user.password_confirmation = user.password
user.roles << Role.find_by_name('Patron')
user.active = true
user.activation_date = Time.now

user.save || puts("unable to create test@test.com user!")

user = User.new
user.email                 = 'notactive@test.com'
user.password              = 'test'
user.password_confirmation = user.password
user.roles << Role.find_by_name('Patron')
user.active = false
user.activation_date = nil # must be nil as this user is not active

user.save || puts("unable to create notactive@test.com user!")

user = User.new
user.email                 = 'admin@test.com'
user.password              = 'test'
user.password_confirmation = user.password
user.roles << Role.find_by_name('Administrator')
user.active = true
user.activation_date = Time.now

user.save || puts("unable to create admin@test.com user!")

Role.find(:all).each do |role|
  user = User.new
  user.email = "#{role.name.downcase}@test.com"
  user.password = role.name.downcase
  user.password_confirmation = user.password
  user.roles << role
  user.active = true
  user.activation_date = Time.now

  user.save || puts("unable to create sample role user user #{role.name}!")
end
